### PR TITLE
Update Schedule Page to use Local Time instead of CST

### PR DESCRIPTION
**Pull request by isaacrlevin**

### CODE REVIEW

**Comment by IEvangelist** [comment]
I don't think this is what we want here. We're using Blazor server-side, not WASM. As a result, this would represent the server's local time... not the clients local time. Unless I'm missing something?

**Comment by isaacrlevin** [comment]
Yea you are right, I need to JSInterop for this, I will fix today

**Comment by isaacrlevin** [comment]
If you want to close it, you can. I do think it makes sense to add some JavaScript update those date fields to local

**Comment by IEvangelist** [comment]
> If you want to close it, you can. I do think it makes sense to add some JavaScript update those date fields to local

We have an episode coming up where [Jon Skeet will be joining us to debug our DateTime bugs](https://dotnetdocs.dev/show/754f063f-7b83-44e0-813d-ef22c02739e9), we'll try to cover this.

**Pull request closed without merging**
